### PR TITLE
feat: add main block to main page

### PR DESCRIPTION
**Pull request by divyanshugarg36**
This will add the main block to the site.

### CODE REVIEW

**Comment by theamanjs** [comment]
@divyanshugarg36 it is suggested to use `chore` when there is no change in production code. If there are changes that are related to production we use feat for that. You can keep this in mind to keep a better track of commits.

**Comment by divyanshugarg36** [comment]
> @divyanshugarg36 it is suggested to use `chore` when there is no change in production code. If there are changes that are related to production we use feat for that. You can keep this in mind to keep a better track of commits.

can you explain this bit more?

**Comment by theamanjs** [comment]
You can refer to this discussion here https://stackoverflow.com/questions/26944762/when-to-use-chore-as-type-of-commit-message Our idea is to keep the chores and features separate and not confuse each other and machines within them. If these two types of commits will be mixed we will not be able to make maximum out of the conventional commits like automatically generated change log, structured history, etc.

**Comment by divyanshugarg36** [comment]
> You can refer to this discussion here https://stackoverflow.com/questions/26944762/when-to-use-chore-as-type-of-commit-message Our idea is to keep the chores and features separate and not confuse each other and machines within them. If these two types of commits will be mixed we will not be able to make maximum out of the conventional commits like automatically generated change log, structured history, etc.

Got it thanks for the explanation

**Comment by theamanjs** [comment]
@divyanshugarg36 can you resolve the conflicts here so that I can approve this reviewed PR.

**Comment by divyanshugarg36** [comment]
@theamanjs Conflicts has been resolved

**Review by theamanjs — APPROVED** [review]

**Pull request merged**
